POST http://localhost:8090/api/public/users/register/
Accept: application/json
Content-Type: application/json

{
  "username": "ianmuhia",
  "password": "*#*Johnte2536",
  "email": "ianmuhia3@gmail.com",
  "full_name": "iano"
}




###
POST http://localhost:8090/api/public/users/login/
Accept: application/json
Content-Type: application/json


{
  "password": "*#*Johnte2536",
  "email": "ianmuhia3@gmail.com"
}


###
POST http://localhost:8090/api/public/users/verifyemail/
Accept: application/json
Content-Type: application/json

{
  "code": "134165",
  "email": "ianmuhia3@gmail.com"
}


####
GET  http://localhost:8090/api/protected/profile/
Accept: application/json
Content-Type: application/json
# Content-Type: multipart/form-data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI3ZDA5M2ViLWVlN2EtNGJlZi1iMmEwLWNjNDZlOGUzMWVjMSIsInVzZXJuYW1lIjoiaWFubXVoaWEzQGdtYWlsLmNvbSIsImlzc3VlZF9hdCI6IjIwMjItMDEtMTFUMDE6NTU6NTAuOTc5NzA3NDM2KzAzOjAwIiwiZXhwaXJlZF9hdCI6IjIwMjItMDEtMTFUMDI6MTU6NTAuOTc5NzA3NTUxKzAzOjAwIn0.XtT0iW-c4GoJvM2Vvs6Typu0NAYBm1_3hSeL82cswXg


###
POST http://localhost:8090/api/protected/create-news/
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNlZDM2NWU3LWExY2YtNGRhNy1hYjhkLTlkNzQwNzg3YzMwNSIsInVzZXJuYW1lIjoiaWFubXVoaWEzQGdtYWlsLmNvbSIsImlzc3VlZF9hdCI6IjIwMjItMDEtMTFUMDI6MjU6NTAuNjI3MzM3MzQ2KzAzOjAwIiwiZXhwaXJlZF9hdCI6IjIwMjItMDEtMTFUMjI6MjU6NTAuNjI3MzM3NDc2KzAzOjAwIn0.X7gl2R6mIEoy169WIjCCOY6dc4l2h0jZ0Cj9JEXNubE



{
  "title": "Test Title",
  "sub_title": "sub_title",
  "content": "Content Test"
}

###
GET http://localhost:8090/api/protected/get-news/
Accept: application/json
Content-Type: application/json
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIyYjg0ZWM2LTEyYWMtNDRkYi05N2M1LTQ2MzMyNzNmMWRmNSIsInVzZXJuYW1lIjoiaWFubXVoaWEzQGdtYWlsLmNvbSIsImlzc3VlZF9hdCI6IjIwMjItMDEtMTFUMTk6Mzg6MzIuMTMxMjY2MTQ5KzAzOjAwIiwiZXhwaXJlZF9hdCI6IjIwMjItMDEtMTJUMTU6Mzg6MzIuMTMxMjY2MzQxKzAzOjAwIn0.q2idYt5oXp4hztP1Cb7VwyZQoyd749hNhv4Dk5onbjM"