POST http://localhost:8090/api/public/users/register/
Accept: application/json
Content-Type: application/json

{
  "username": "ianmuhia",
  "password": "*#*Johnte2536",
  "email": "ianmuhia3@gmail.com",
  "full_name": "iano"
}




###
POST http://localhost:8090/api/auth/users/login/
Accept: application/json
Content-Type: application/json


{
  "password": "*#*Johnte2536",
  "email": "ianmuhia3@gmail.com"
}
> {%
    client.global.set("auth_token", response.body.access_token);
%}


###
POST http://localhost:8090/api/public/users/verifyemail/
Accept: application/json
Content-Type: application/json

{
  "code": "951562",
  "email": "ianmuhia3@gmail.com"
}


####
GET  http://localhost:8090/api/protected/profile/
Accept: application/json
Content-Type: application/json
# Content-Type: multipart/form-data
Authorization: Bearer {{auth_token}}


###
POST http://localhost:8090/api/protected/create-news/
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}



{
  "title": "Test Title",
  "sub_title": "sub_title",
  "content": "Content Test"
}

###
GET http://localhost:8090/api/protected/get-news/
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}


###
GET http://localhost:8090/api/protected/get-users/
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}