POST http://localhost:8090/api/auth/users/register/
Accept: application/json
Content-Type: application/json

{
  "username": "ianmuhia",
  "password": "*#*Johnte2536",
  "email": "ianmuhia3@gmail.com",
  "full_name": "iano"
}




###
POST http://192.168.100.17:8090/api/auth/users/login/
Accept: application/json
Content-Type: application/json


{
  "password": "*#*Johnte2536",
  "email": "ianmuhia3@gmail.com"
}
> {%
    client.global.set("auth_token", response.body.access_token);
%}


###
POST http://localhost:8090/api/public/users/verifyemail/
Accept: application/json
Content-Type: application/json

{
  "code": "951562",
  "email": "ianmuhia3@gmail.com"
}


####
GET  http://localhost:8090/api/protected/profile/
Accept: application/json
Content-Type: application/json
# Content-Type: multipart/form-data
Authorization: Bearer {{auth_token}}


###
POST http://localhost:8090/api/protected/create-news/
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}



{
  "title": "Test Title",
  "sub_title": "sub_title",
  "content": "Content Test"
}

###
GET http://localhost:8090/api/protected/get-news/
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}


###
GET http://localhost:8090/api/protected/get-users/
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}


###
GET http://localhost:8090/api/protected/get-events/
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###
GET https://bible-api.com/john%2011:1

###
GET http://localhost:8090/api/protected/get-author-events/?id=3
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###
DELETE http://localhost:8090/api/protected/delete-event/?id=1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}


###
GET https://api.mapbox.com/geocoding/v5/mapbox.places/-1.0375398381976182, 37.071626628996015.json?access_token=pk.eyJ1IjoiaWFubXVoaWEiLCJhIjoiY2t5eXR3dHBlMDdxdDJ1bzFoNnU0NzFsZiJ9.qY6KRbgPY-BvLDe3528Kyg


###

# curl "https://api.mapbox.com/geocoding/v5/mapbox.places/donut.json?type=poi&proximity=-74.70850,40.78375&access_token=pk.eyJ1IjoiaWFubXVoaWEiLCJhIjoiY2t5eXR3dHBlMDdxdDJ1bzFoNnU0NzFsZiJ9.qY6KRbgPY-BvLDe3528Kyg"
GET https://api.mapbox.com/geocoding/v5/mapbox.places/church.json?type=poi&proximity=-1.0560805436017364, 37.073510758481284&country=ke&access_token=pk.eyJ1IjoiaWFubXVoaWEiLCJhIjoiY2t5eXR3dHBlMDdxdDJ1bzFoNnU0NzFsZiJ9.qY6KRbgPY-BvLDe3528Kyg

###
GET https://api.mapbox.com/geocoding/v5/mapbox.places/donut.json?country=Ke&type=poi&proximity=-1.0264,37.0672&access_token=pk.eyJ1IjoiaWFubXVoaWEiLCJhIjoiY2t5eXR3dHBlMDdxdDJ1bzFoNnU0NzFsZiJ9.qY6KRbgPY-BvLDe3528Kyg



###

https://api.mapbox.com/geocoding/v5/mapbox.places/church.json?country=ke&proximity=-1.0264%2C37.0672&types=poi&access_token=pk.eyJ1IjoiaWFubXVoaWEiLCJhIjoiY2t5eXR3dHBlMDdxdDJ1bzFoNnU0NzFsZiJ9.qY6KRbgPY-BvLDe3528Kyg