version: "3.8"


services:
  database:
    image: postgres:latest
    container_name: postgres_clj
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  app:
    container_name: clj-dev
    image: clj-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - database
    env_file: .env

volumes:
  dbdata: