version: "3.8"


services:
  database:
    image: postgres:latest
    container_name: postgres_clj
    restart: always
    networks:
      - fullstack
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  app:
    container_name: clj-dev
    image: clj-dev
    restart: on-failure
    networks:
      - fullstack
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - database
    env_file: .env

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - database
    ports:
      - "5050:80"
    networks:
      - fullstack
    restart: unless-stopped

volumes:
  dbdata:

networks:
  fullstack:
    driver: bridge