// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type News struct {
	ID         int64
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
	DeletedAt  sql.NullTime
	AuthorID   sql.NullInt64
	CoverImage sql.NullString
	Title      sql.NullString
	SubTitle   sql.NullString
	Content    sql.NullString
}

type User struct {
	ID           int64
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullTime
	UserName     string
	FullName     string
	Email        string
	PasswordHash string
	ProfileImage sql.NullString
	IsVerified   sql.NullBool
}
